### ISSUE TITLE
program shutdown when unable to communicate to the api server

### ISSUE THREAD

**Issue by jor8888** [Taschenbuch/Gw2TinyWvwKillCounter#2] opened 2021-08-01 18:31 UTC
program shutdown when unable to communicate to the api server

**Comment by Taschenbuch** [comment] 2021-08-01 19:59
Is already fixed in version 2 which is not released yet. It will still shutdown when api server is not available on program startup or on api key change. But it will not shut down anymore when it is already running and the api server becomes unavailable then.

**Comment by Taschenbuch** [comment] 2021-08-08 14:11
fixed in version 2

**Comment by Taschenbuch** [comment] 2021-08-15 14:48
Still not fixed i think. At least i found some crashes that are not caught though they should be caught

**Comment by jor8888** [comment] 2021-08-15 15:23
still crashing on version 2

**Comment by Taschenbuch** [comment] 2021-08-15 16:05
> still crashing on version 2

can you copy the error message you get and post it here? Ctrl + c after clicking into the error message window and then ctrl + v to copy it into a comment here.

I think i know the reason why it does not work yet, but I dont know if you experience the same crash reasons as I do. Would be usefull to see the exact error message you get.

**Comment by jor8888** [comment] 2021-08-15 23:18
![err](https://user-images.githubusercontent.com/76445398/129495601-8ba6b8ad-57ed-4e1f-b435-32d64b5d45ac.jpg)

**Comment by jor8888** [comment] 2021-08-15 23:19
---------------------------
Sorry, Gw2TinyWvwKillCounter crashed :(
---------------------------
Gw2Sharp.WebApi.Exceptions.RequestCanceledException: Request was canceled

   at Gw2Sharp.WebApi.Http.HttpClient.<>c__DisplayClass11_0.<<RequestStreamAsync>g__ExecAsync|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Gw2Sharp.WebApi.Http.HttpClient.RequestAsync(IWebApiRequest request, CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.Middleware.ExceptionMiddleware.<>c__DisplayClass1_0.<<OnRequestAsync>g__ExecAsync|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Gw2Sharp.WebApi.Middleware.RequestSplitterMiddleware.<>c__DisplayClass4_0.<<OnRequestAsync>g__ExecAsync|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Gw2Sharp.WebApi.Middleware.CacheMiddleware.RequestGetAsync(String cacheCategory, String cacheId, MiddlewareContext context, Func`3 callNext, CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.Caching.BaseCacheMethod.<>c__DisplayClass4_0.<<GetOrUpdateAsync>g__ExecAsync|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Gw2Sharp.WebApi.Middleware.CacheMiddleware.OnAllRequestAsync(MiddlewareContext context, Func`3 callNext, CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.Http.WebApiRequest.ExecuteAsync[TResponse](CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.V2.Clients.BaseEndpointBulkAllClient`2.AllAsync(CancellationToken cancellationToken)

   at Gw2TinyWvwKillCounter.Api.KillDeathService.GetTotalKillsAndDeaths(Gw2Client gw2Client)

   at Gw2TinyWvwKillCounter.Api.KillDeathService.GetKillsAndDeaths()

   at Gw2TinyWvwKillCounter.ViewAndViewModels.MainViewModel.OnAsyncTimerIntervalEnded(Object sender, EventArgs e)

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by Taschenbuch** [comment] 2021-08-16 16:38
interesting. I get other api errors. Your error is probably caused by a timeout (30 seconds). The current workaround catches only certain types of errors (but even fails doing that :D). But I probably gonna implement something that simply catches every possible error and ignore them to prevent the crashes.

**Comment by jor8888** [comment] 2021-08-16 20:36
---------------------------
Sorry, Gw2TinyWvwKillCounter crashed :(
---------------------------
Gw2Sharp.WebApi.Exceptions.RequestException: Request error: One or more errors occurred. (The SSL connection could not be established, see inner exception.)

 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain

   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)

   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.Http.HttpClient.<>c__DisplayClass11_0.<<RequestStreamAsync>g__ExecAsync|0>d.MoveNext()

   --- End of inner exception stack trace ---

   at Gw2Sharp.WebApi.Http.HttpClient.<>c__DisplayClass11_0.<<RequestStreamAsync>g__ExecAsync|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Gw2Sharp.WebApi.Http.HttpClient.RequestAsync(IWebApiRequest request, CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.Middleware.ExceptionMiddleware.<>c__DisplayClass1_0.<<OnRequestAsync>g__ExecAsync|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Gw2Sharp.WebApi.Middleware.RequestSplitterMiddleware.<>c__DisplayClass4_0.<<OnRequestAsync>g__ExecAsync|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Gw2Sharp.WebApi.Middleware.CacheMiddleware.RequestGetAsync(String cacheCategory, String cacheId, MiddlewareContext context, Func`3 callNext, CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.Caching.BaseCacheMethod.<>c__DisplayClass4_0.<<GetOrUpdateAsync>g__ExecAsync|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Gw2Sharp.WebApi.Middleware.CacheMiddleware.OnAllRequestAsync(MiddlewareContext context, Func`3 callNext, CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.Http.WebApiRequest.ExecuteAsync[TResponse](CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.V2.Clients.BaseEndpointBulkAllClient`2.AllAsync(CancellationToken cancellationToken)

   at Gw2TinyWvwKillCounter.Api.KillDeathService.GetTotalKillsAndDeaths(Gw2Client gw2Client)

   at Gw2TinyWvwKillCounter.Api.KillDeathService.GetKillsAndDeaths()

   at Gw2TinyWvwKillCounter.ViewAndViewModels.MainViewModel.OnAsyncTimerIntervalEnded(Object sender, EventArgs e)

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by Taschenbuch** [comment] 2021-08-17 18:24
thanks, those error reports. They are really helpfull. It is interesting because I get other api errors. Your first error is probably caused by a timeout (30 seconds). The second error, i dont know yet.
The version 2 fix catched only certain types of errors (but even fails doing that :D), but even if it would have worked, it would not have catched your kind of errors. I now added a more general error catcher as a workaround and released it as version 3 alpha. You can download it here (warning: i didnt test it yet):

https://github.com/Taschenbuch/Gw2TinyWvwKillCounter/releases/download/version_3_alpha/Gw2TinyWvwKillCounter.exe

**Comment by jor8888** [comment] 2021-08-25 13:34
---------------------------
Sorry, Gw2TinyWvwKillCounter crashed :(
---------------------------
Gw2Sharp.WebApi.Exceptions.RequestException: Request error: One or more errors occurred. (The SSL connection could not be established, see inner exception.)

 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.

   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)

   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)

   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.Http.HttpClient.<>c__DisplayClass11_0.<<RequestStreamAsync>g__ExecAsync|0>d.MoveNext()

   --- End of inner exception stack trace ---

   at Gw2Sharp.WebApi.Http.HttpClient.<>c__DisplayClass11_0.<<RequestStreamAsync>g__ExecAsync|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Gw2Sharp.WebApi.Http.HttpClient.RequestAsync(IWebApiRequest request, CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.Middleware.ExceptionMiddleware.<>c__DisplayClass1_0.<<OnRequestAsync>g__ExecAsync|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Gw2Sharp.WebApi.Middleware.RequestSplitterMiddleware.<>c__DisplayClass4_0.<<OnRequestAsync>g__ExecAsync|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Gw2Sharp.WebApi.Middleware.CacheMiddleware.RequestGetAsync(String cacheCategory, String cacheId, MiddlewareContext context, Func`3 callNext, CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.Caching.BaseCacheMethod.<>c__DisplayClass4_0.<<GetOrUpdateAsync>g__ExecAsync|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Gw2Sharp.WebApi.Middleware.CacheMiddleware.OnEndpointRequestAsync(MiddlewareContext context, Func`3 callNext, CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.Http.WebApiRequest.ExecuteAsync[TResponse](CancellationToken cancellationToken)

   at Gw2Sharp.WebApi.V2.Clients.BaseEndpointBlobClient`1.GetAsync(CancellationToken cancellationToken)

   at Gw2TinyWvwKillCounter.Api.KillDeathService.GetTotalKillsAndDeaths(Gw2Client gw2Client)

   at Gw2TinyWvwKillCounter.Api.KillDeathService.InitialiseAndGetTotalKillsDeath(String apiKey)

   at Gw2TinyWvwKillCounter.ViewAndViewModels.MainViewModel.StartCallingApiIfApiKeyIsValid()

   at Gw2TinyWvwKillCounter.ViewAndViewModels.MainViewModel.OnWindowLoaded()

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by jor8888** [comment] 2021-08-28 23:26
been working good except error message at startup when there was no connection.

**Comment by Taschenbuch** [comment] 2022-03-28 16:49
Will not be fixed in the current stand alone version. But the tool will be integrated as a blish hud module in the future. And there it will not have this issue anymore because i gonna add additonal error handling on start up.

**Closed by Taschenbuch** 2022-03-28 16:49 UTC
Labels: bug
